# Relative path(s) to your source files
source: src/assets/scss/

# Relative path where you want the documentation to be built
destination: web/styleguide

# The path that contains supporting assets for the documentation page
documentation_assets: src/assets/vendor/hologram-github-theme

# Category that will be used as the index.html (optional)
index: styleguide

# A list of relative paths to folders containing any dependencies to copy
dependencies:
  - 'src/templates'
  - 'src/assets/vendor'

# The CSS files to be included in the styleguide
css_include:
  - '/assets/styles/legacy.css'
  - '/assets/styles/modern.css'


# The global title that is displayed at the top of the pages
global_title: Styleguide
